title: Tiny 日本語
description: Something you can panic study with a week left before you go
theme: just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
